config/routes.rb
Rails.application.routes.draw do
  root to: 'games#new'
  get 'new', to: 'games#new'
  post 'score', to: 'games#score'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'json'
require 'open-uri'

class GamesController < ApplicationController
  def new
    @letters = generate_grid
    @player_guess = ''
  end

  def score
    @player_guess = params[:word].downcase
    @letters = params[:grid].split(" ")
    @start_time = params[:start_time]

    @result = run_game
  end

  private

  def generate_grid
    letters = ('a'..'z').to_a.shuffle * 10
    letters.take(10)
  end

  def can_build_word?
    @player_guess.chars.all? { |c| @letters.count(c) >= 1 }
  end

  def english_word?
    url = "https://wagon-dictionary.herokuapp.com/#{@player_guess}"
    word = JSON.parse(open(url).read)
    word['found']
  end

  def run_game
    if can_build_word? && english_word?
      "Well done!"
    elsif !english_word?
      "Sorry, '#{@player_guess.upcase}' doesn't seem to be an english word."
    elsif !can_build_word?
      "Sorry, cannot build '#{@player_guess.upcase}' out of '#{@letters.join(' - ').upcase}'."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>Longest Word Challenge</h1>
<div class="letters-grid">
  <% @letters.each do |letter| %>
    <div class="letter"><%= letter.upcase %></div>
  <% end %>
</div>

<%= simple_form_for @player_guess, url: score_path, method: :post, html: { class: "user-input" } do |f| %>
  <%= f.input :word, label: false, placeholder: "Your guess...", input_html: { style: 'width: 200px' } %>
  <%= f.submit 'Play', class: 'btn btn-info w-100' %>
  <%= hidden_field_tag 'grid', @letters %>
  <%= hidden_field_tag 'start_time', Time.now %>
<% end %>

app/views/games/score.html.erb
<h1>Longest Word Challenge</h1>

<div class="result">
  <div class="upper-part">
    <h3 class="text-center border-bottom">Result</h3>

    <p class="result-string text-center"><%= @result %></p>
  </div>

  <%= link_to 'Play again', new_path, class: 'btn btn-info play-again-btn'  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGameReboot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="game-container">
      <%= yield %>
    </div>
  </body>
</html>